// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "integration-go/entity"

	mock "github.com/stretchr/testify/mock"
)

// RoomRepository is an autogenerated mock type for the roomRepository type
type RoomRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *RoomRepository) FindByID(ctx context.Context, id int64) (*entity.Room, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Room); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *RoomRepository) Save(ctx context.Context, _a1 *entity.Room) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Room) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoomRepository creates a new instance of RoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomRepository {
	mock := &RoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
