with-expecter: True
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
mockname: "{{.InterfaceName | camelcase}}"
filename: "{{.InterfaceName | snakecase}}.go"
all: True
packages:
  integration-go:
    config:
      recursive: True
      exclude: [internal/api, internal/qismo]