pipelines:
  branches:
    staging:
      - step:
          name: Test
          runs-on:
            - "self.hosted"
            - "linux"
          image: golang:1.22.3
          script:
            - make test
      - step:
          name: Build and Publish
          runs-on:
            - "self.hosted"
            - "linux"
          services:
            - docker
          script:
            - export REGISTRY=registry-stage.qiscus.io/integration/
            - export PROJECT="${BITBUCKET_REPO_SLUG}-${BITBUCKET_BRANCH}"
            - export IMAGE="${REGISTRY}${PROJECT}"
            - export DOCKER_BUILDKIT=1
            - docker build -t $IMAGE:$BITBUCKET_BUILD_NUMBER .
            - echo ${HARBOR_PASSWORD} | docker login registry-stage.qiscus.io --username ${HARBOR_USER} --password-stdin
            - docker push $IMAGE:$BITBUCKET_BUILD_NUMBER
            - echo $IMAGE:$BITBUCKET_BUILD_NUMBER
      - step:
          name: Update Central Application
          trigger: manual
          image:
            name: registry-stage.qiscus.io/integration/central-command:stable
            username: $HARBOR_USER
            password: $HARBOR_PASSWORD
          deployment: staging
          script:
            - export REGISTRY=registry-stage.qiscus.io/integration/
            - export PROJECT="${BITBUCKET_REPO_SLUG}-${BITBUCKET_BRANCH}"
            - export IMAGE="${REGISTRY}${PROJECT}"
            - chmod +x /app/central
            - /app/central -n $PROJECT -i $IMAGE:$BITBUCKET_BUILD_NUMBER
options:
  docker: true
