// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Omnichannel is an autogenerated mock type for the Omnichannel type
type Omnichannel struct {
	mock.Mock
}

// CreateRoomTag provides a mock function with given fields: ctx, roomID, tag
func (_m *Omnichannel) CreateRoomTag(ctx context.Context, roomID string, tag string) error {
	ret := _m.Called(ctx, roomID, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoomTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roomID, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOmnichannel creates a new instance of Omnichannel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOmnichannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *Omnichannel {
	mock := &Omnichannel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
