// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Omnichannel is an autogenerated mock type for the Omnichannel type
type Omnichannel struct {
	mock.Mock
}

type Omnichannel_Expecter struct {
	mock *mock.Mock
}

func (_m *Omnichannel) EXPECT() *Omnichannel_Expecter {
	return &Omnichannel_Expecter{mock: &_m.Mock}
}

// ResolvedRoom provides a mock function with given fields: ctx, roomID
func (_m *Omnichannel) ResolvedRoom(ctx context.Context, roomID string) error {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ResolvedRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Omnichannel_ResolvedRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvedRoom'
type Omnichannel_ResolvedRoom_Call struct {
	*mock.Call
}

// ResolvedRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *Omnichannel_Expecter) ResolvedRoom(ctx interface{}, roomID interface{}) *Omnichannel_ResolvedRoom_Call {
	return &Omnichannel_ResolvedRoom_Call{Call: _e.mock.On("ResolvedRoom", ctx, roomID)}
}

func (_c *Omnichannel_ResolvedRoom_Call) Run(run func(ctx context.Context, roomID string)) *Omnichannel_ResolvedRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Omnichannel_ResolvedRoom_Call) Return(_a0 error) *Omnichannel_ResolvedRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Omnichannel_ResolvedRoom_Call) RunAndReturn(run func(context.Context, string) error) *Omnichannel_ResolvedRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewOmnichannel creates a new instance of Omnichannel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOmnichannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *Omnichannel {
	mock := &Omnichannel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
